### PR TITLE
Always request English version of pages

### LINKED ISSUE #263: Displaying authentication code does not work in other languages
[Looking at this commit, the logic for displaying the authentication code will not work on pages that use other languages.](https://github.com/aws-azure-login/aws-azure-login/commit/21574d056b935bc44a8f6585e443985679267a28)  We have devs working internationally using the tool, but once we required these authentication codes in Azure it breaks for our international colleagues.

Essentially there is german output saying that you need to enter the authentication code displayed and the console doesn't display the code.  If you run the application using the GUI mode, it is there on the page.

Screenshot 2023-02-03 at 10 43 09 AM

Attached is the HTML page of a German authentication page, if that helps.  I've tried to clear out as much identifying information as I can.

[german-2fa-response.html.txt](https://github.com/aws-azure-login/aws-azure-login/files/10580814/german-2fa-response.html.txt)

### PR DESCRIPTION
**Pull request by guerda**
Changing the Azure language or the Windows OS language doesn't fix the fix in #263. The headless Chromium still requests a language which is not English in my case. Therefore the identification for the number in the "number matching" 2FA mechanism doesn't work.

Requesting the English version of the login page explicitly allows to identify and extract the digits for the "number matching" mechanism. Works for me with a seemingly German Azure account.

Fixes #263

### CODE REVIEW

File: src/login.ts [hunk 1]
```diff
@@ -726,6 +726,9 @@ export const login = {
 
       const pages = await browser.pages();
       const page = pages[0];
+      await page.setExtraHTTPHeaders({
+        "Accept-Language": "en",
```
Comment (MohamedAsan) [inline src/login.ts:730]: Remove this comma
```suggestion
        "Accept-Language": "en"
```

**Review by MohamedAsan — CHANGES_REQUESTED** [review]

File: src/login.ts (hunk 1 above)
Comment (guerda) [reply src/login.ts:730]: This comma was added by prettier as configured, you sure?

Comment (MohamedAsan) [reply src/login.ts:730]: Alright 👍

**Review by MohamedAsan — APPROVED** [review]

**Comment by guerda** [comment]
Thank you for reviewing and merging, Mohamed!
